abbr rm "rm -I"
abbr cp "cp -i"
abbr mv "mv -i"
abbr mkdir "mkdir -p"
abbr h "history"
abbr which "type -a"
abbr ls "eza -lag --header"
abbr cd "z"
abbr vim "nvim"
abbr vi "nvim"
abbr vfc "nvim ~/.config/fish/config.fish && source ~/.config/fish/config.fish"
abbr vfa "nvim ~/.config/fish/conf.d/abbr.fish && source ~/.config/fish/config.fish"
abbr k "kubectl"
abbr kaf "kubectl apply -f"
abbr kcs "kubectl config set-context --current --namespace"
abbr kd "kubectl describe"
abbr ke "kubectl exec -it"
abbr kg "kubectl get"
abbr kgp "kubectl get pods"
abbr kl "kubectl logs"
abbr klf "kubectl logs -f"
abbr kpf "kubectl port-forward"
abbr krm "kubectl delete"
abbr tf "terraform"
abbr tfa "terraform apply"
abbr tfaa "terraform apply --auto-approve"
abbr tfi "terraform init"
abbr tfp "terraform plan"
abbr tfu "terraform force-unlock"
abbr gcam --set-cursor=% "git commit -a -m '%'"
abbr gcm --set-cursor=% "git commit -m '%'"
