abbr rm "rm -I"
abbr cp "cp -i"
abbr mv "mv -i"
abbr mkdir "mkdir -p"
abbr h "history"
abbr which "type -a"
abbr ls "eza -lag --header"
abbr cd "z"
abbr vim "nvim"
abbr vi "nvim"
abbr vfc "nvim ~/.config/fish/config.fish && source ~/.config/fish/config.fish"
abbr vfa "nvim ~/.config/fish/conf.d/abbr.fish && source ~/.config/fish/config.fish"
abbr k "kubectl"
abbr kg "kubectl get"
abbr kgp "kubectl get pods"
abbr kd "kubectl describe"
abbr kcs "kubectl config set-context --current --namespace"
abbr kl "kubectl log"
abbr klf "kubectl log -f"
abbr ke "kubectl exec -it"
abbr tf "terraform"
